# Generated by Django 3.2.4 on 2021-06-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_by',
        ),
    ]
