# Generated by Django 3.2.4 on 2021-06-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_by',
        ),
    ]
